name: dnabert_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10  # For PyTorch compatibility
  # Core dependencies
  - pip
  - numpy<2.0.0
  - pandas>=1.3.0
  - scikit-learn>=0.24.2
  - pyarrow>=6.0.0
  # Bioinformatics
  - biopython>=1.79
  - viennarna>=2.5.0
  # Jupyter environment
  - notebook=6.4.12  # Fixed version for compatibility
  - jupyterlab=3.2.8  # Fixed version
  - ipywidgets=7.6.5  # Fixed version
  - jupyter_core>=4.9.2
  - nbformat>=5.1.3
  - ipython>=8.0.1
  # Visualization
  - matplotlib>=3.4.3
  - seaborn>=0.11.2
  # Development tools
  - pytest>=7.0.0
  - pytest-cov>=3.0.0
  - pytest-mock>=3.6.1
  - coverage>=6.2
  - black>=22.3.0
  - flake8>=4.0.1
  - pylint>=2.12.2
  - mypy>=0.931
  # Build tools
  - setuptools>=60.5.0
  - wheel>=0.37.1
  - pip:
    # Deep learning (PyTorch will be installed by setup_env.sh)
    - transformers>=4.5.0
    - datasets>=2.0.0
    - sentencepiece>=0.1.96
    - regex>=2022.1.18
    # Project dependencies
    - geoparse>=1.0.0
    - tqdm>=4.62.3
    # Testing
    - pytest-env>=0.6.2
    # Documentation
    - sphinx>=4.4.0
    - sphinx-rtd-theme>=1.0.0
    - sphinx-autodoc-typehints>=1.12.0
    # Type checking
    - types-PyYAML>=6.0.1
    - types-requests>=2.27.7
    - typing-extensions>=4.0.1
    # Development
    - pre-commit>=2.17.0
    - bandit>=1.7.1
    - safety>=1.10.3
    # Build
    - build>=0.7.0
    - twine>=3.8.0

# Installation and setup:
# 1. Create environment:
#    conda env create -f environment.yml
# 
# 2. Activate environment:
#    conda activate dnabert_env
# 
# 3. Run setup script for PyTorch installation:
#    ./setup_env.sh